//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindLandFill.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waste
    {
        public long WasteID { get; set; }
        public string WasteType { get; set; }
        public Nullable<double> WasteCosts { get; set; }
    }
}
